---
- name: "Install dnf-automatic package"
  ansible.builtin.package:
    name: dnf-automatic
    state: present
  tags: dnf-automatic

- name: "Configure dnf-automatic"
  ansible.builtin.template:
    src: dnf-automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart dnf-automatic
  tags: dnf-automatic

- name: "Enable and start dnf-automatic timer"
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    enabled: true
    state: started
  tags: dnf-automatic
