---
- name: "Copy script for /etc/profile.d"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/profile.d/{{ item }}"
    owner: root
    group: root
    mode: "0755"
  with_items: "{{ prompt_profiled }}"
  tags: prompt

- name: "Copy files"
  ansible.builtin.copy:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  notify: "Update font cache"
  with_items:
    - source: "../files/prompt/powerline-go-v{{ prompt_powerline_go_version }}-{{ ansible_system | lower }}-{{ ansible_architecture }}"
      dest: "/usr/local/bin/powerline-go{{ '.exe' if ansible_system | lower == 'windows' else '' }}"
      mode: "0755"
    - source: "../files/prompt/yq-v{{ prompt_yq_version }}-{{ ansible_system | lower }}-{{ ansible_architecture }}{"
      dest: "/usr/local/bin/yq{{ '.exe' if ansible_system | lower == 'windows' else '' }}"
      mode: "0755"
    - source: "../files/prompt/bcrypt"
      dest: "/usr/local/bin/bycrypt"
      mode: "0755"
    - source: "../files/prompt/SourceCodePro.ttf"
      dest: "/usr/share/fonts/SourceCodePro.ttf"
      mode: "0644"
    - source: ../files/bashrc/ms.sh
      dest: "/root/.ms.sh"
      mode: "0755"
    - source: ../files/bashrc/tmux.conf
      dest: "/root/.tmux.conf"
      mode: "0644"
    - source: ../files/bashrc/vimrc
      dest: "/root/.vimrc"
      mode: "0644"
    - source: ../files/bashrc/gitconfig
      dest: "/root/.gitconfig"
      mode: "0644"
  tags: prompt
