---
- name: "Gather operating system variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags: vmware_tools

- name: "Install package"
  ansible.builtin.package:
    name: "{{ vmware_package_name }}"
    state: present
  environment: "{{ proxy_env }}"
  tags: vmware_tools

- name: "Start and enable service"
  ansible.builtin.service:
    name: "{{ vmware_service_name }}"
    state: started
    enabled: true
  tags: vmware_tools
