---
- name: "Gather operating system variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags: msmtp

- name: "Install msmtp package"
  ansible.builtin.package:
    name: "{{ msmtp_packages }}"
    state: present
  environment: "{{ proxy_env }}"
  tags: msmtp

- name: "Configure msmtp"
  ansible.builtin.template:
    src: msmtprc.j2
    dest: "{{ msmtp_config_file }}"
    mode: '0600'
    owner: "{{ msmtp_user }}"
    group: "{{ msmtp_group }}"
  tags: msmtp

- name: "Configure /etc/aliases"
  ansible.builtin.template:
    src: aliases.j2
    dest: "{{ msmtp_aliases_file }}"
    mode: '0644'
    owner: "{{ msmtp_user }}"
    group: "{{ msmtp_group }}"
  when: msmtp_aliases | length > 0
  tags: msmtp

- name: "Set msmtp as the default MTA on Debian and RedHat"
  community.general.alternatives:
    name: mta
    link: /usr/sbin/sendmail
    path: /usr/bin/msmtp
  when: ansible_os_family in ['Debian', 'RedHat']
  tags: msmtp

- name: "Set msmtp as the default MTA on SUSE"
  ansible.builtin.command:
    cmd: update-alternatives --set mta /usr/bin/msmtp
  when: ansible_os_family == "Suse"
  tags: msmtp

- name: "Set msmtp as the default MTA on OpenBSD"
  ansible.builtin.file:
    src: /usr/local/bin/msmtp
    dest: /usr/sbin/sendmail
    state: link
  when: ansible_os_family == "OpenBSD"
  tags: msmtp
