---
- name: "Add repository"
  ansible.builtin.zypper_repository:
    name: Docker CE Stable - x86_64
    repo: https://download.docker.com/linux/sles/docker-ce.repo
    state: present
  tags: docker

- name: "Install packages"
  ansible.builtin.zypper:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  tags: docker
