---
- name: "Reload firewalld"
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  tags: firewalld

- name: "Restart firewalld"
  ansible.builtin.service:
    name: firewalld
    state: restarted
  tags: firewalld
