- name: "Combine lvm_config"
  ansible.builtin.set_fact:
    lvm_config: >-
      {{
        (defaults_lvm_config | default([])) +
        (group_vars_lvm_config | default([])) +
        (host_vars_lvm_config | default([])) +
        (playbook_lvm_config | default([]))
      | unique }}
  tags: lvm

# - name: "Debug lvm_config"
#   ansible.builtin.debug:
#     msg: "{{ lvm_config }}"
#   tags:
#     - lvm

- name: "Install necessary packages"
  ansible.builtin.package:
    name:
      - lvm2
      - xfsprogs
    state: present
  tags: lvm

- name: "Create volume groups"
  community.general.lvg:
    vg: "{{ item.vg }}"
    pvs: "{{ item.pv }}"
    force: "{{ item.force | default(false) }}"
  loop: "{{ lvm_config }}"
  tags: lvm

- name: "Create logical volumes"
  community.general.lvol:
    vg: "{{ lv.0.vg }}"
    lv: "{{ lv.1.lv }}"
    size: "{{ lv.1.size }}"
  loop: "{{ lvm_config | subelements('logical_volumes') }}"
  loop_control:
    loop_var: lv
  tags: lvm

- name: "Create filesystems"
  community.general.filesystem:
    fstype: "{{ lv.1.fs_type | default('xfs') }}"
    dev: "/dev/{{ lv.0.vg }}/{{ lv.1.lv }}"
  loop: "{{ lvm_config | subelements('logical_volumes') }}"
  loop_control:
    loop_var: lv
  tags: lvm

- name: "Create data folders"
  ansible.builtin.file:
    path: "{{ lv.1.mount }}"
    state: directory
    mode: "0755"
  loop: "{{ lvm_config | subelements('logical_volumes') }}"
  loop_control:
    loop_var: lv
  tags: lvm

- name: "Mount the volumes"
  ansible.posix.mount:
    path: "{{ lv.1.mount }}"
    src: "/dev/{{ lv.0.vg }}/{{ lv.1.lv }}"
    fstype: "{{ lv.1.fs_type | default('xfs') }}"
    opts: "{{ lv.1.opts | default('defaults') }}"
    state: mounted
  loop: "{{ lvm_config | subelements('logical_volumes') }}"
  loop_control:
    loop_var: lv
  notify: "Reload systemd"
  tags: lvm
