---
smtp_user: "default@example.com"
smtp_host: "smtp.example.com:587"
dnf_automatic_conf_apply_updates: "yes"
dnf_automatic_conf_emit_via: "email"
dnf_automatic_conf_email_from: "{{ smtp_user }}"
dnf_automatic_conf_email_to: "{{ smtp_user }}"
dnf_automatic_conf_email_host: "{{ smtp_host.split(':')[0] }}"
dnf_automatic_conf_email_tls: "yes"
dnf_automatic_conf_email_port: "{{ smtp_host.split(':')[1] }}"
dnf_automatic_conf_download_updates: "yes"
dnf_automatic_conf_download_updates_command: "/usr/bin/dnf-automatic-install"
dnf_automatic_conf_random_sleep: "1800"
dnf_automatic_conf_system_name: "{{ ansible_hostname + '.' + ansible_domain if ansible_domain is defined and ansible_domain != '' else '' }}"
dnf_automatic_conf_system_package_cache: "yes"
dnf_automatic_conf_upgrade_type: "default"
dnf_automatic_conf_reboot: "yes"
